### ISSUE TITLE
Dropbox back-end bug

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/django-dbbackup#26]
Example file content: line1 line2
If use dropbox=2.2.0 package (or 2.1, or 2.0), I will get file with incorrect content: b"line1\nline2"
But if I use dropbox==1.6 package to upload file, I will get file with correct content.

**Comment by dimka665** [comment]
Restore formatting after import from bitbucket.

file content:
line1
line2

dropbox>=2.0 package creates file with incorrect content:
b"line1\nline2"

**Comment by dimka665** [comment]
Can be closed
