### ISSUE TITLE
mediabackup uses a lot of memory

### ISSUE THREAD

**Issue by mjs7231** [mjs7231/django-dbbackup#27]
When I run mediabackup to back up to Amazon S3, it consumes a lot of memory. I'm guessing it might load all the files into memory?
Not sure if there's anything that can be done about it but I thought I'd ask:

    myuser - 372MB - 0:01:02 - 1189 - /home/myuser/.virtualenvs/live/bin/python /home/myuser/webapps/live/myproject/manage.py mediabackup

The media directory is around 331MB.
I'm using django-dbbackup version 2.0.4.

**Comment by dimka665** [comment]
Change max size to 10 Mb fix it.
https://github.com/mjs7231/django-dbbackup/blob/master/dbbackup/utils.py#L102

**Comment by mjs7231** [comment]
All set.
