### ISSUE TITLE
Release 2.05 to pypi

### ISSUE THREAD

**Issue by gardenia** [mjs7231/django-dbbackup#48]
There are a few (at least 2 I know of) breaking bugs in the current pypi release (2.04) which have since been fixed in master.  I was involved with a couple of the fixes on the old bitbucket repo.

The ones I'm aware of are:
* --compress option chews up far too much memory on larger DBs
* --clean option broken due to "dbcommands.filter_filepaths" being removed in refactoring

It would be great if you could upload a release so that the better stability in master is reflected in the pypi release.

Thanks.

**Comment by mjs7231** [comment]
Done! -- Sorry for the delay.
